version: "3"
services:
  database:
    image: postgres:13-alpine
    env_file:
      - ./env/.env.local
    ports:
      - 5432:5432
    volumes:
      - hemli-db-data:/var/lib/postgresql/data/
      
volumes:
  hemli-db-data: